### ISSUE TITLE
FTUE Share my link wrong colour

### ISSUE THREAD

**Issue by laurelterlesky** [thunderbird/appointment#655] opened 2024-09-11 18:25 UTC
On the finish page for the FTUE flow, the share my link is the wrong colour causing low contrast (#a11y issue)

Currently, it is displaying TBA primary for dark mode (A3ECE3), please correct to TBA primary light mode: (008080)

Issue: <img width="827" alt="Screenshot 2024-09-11 at 10 29 38" src="https://github.com/user-attachments/assets/6ca24901-04fa-4ee1-a5eb-387b07120d71">

Correction: 
![Screenshot 2024-09-11 at 11 24 54](https://github.com/user-attachments/assets/7ea3d446-745d-41d5-be21-6fa43d336109)

[Figma reference file](https://www.figma.com/design/hbXmyeGmHepX61zrqrHSaD/TBA_2024_Q2_FTUE?node-id=4503-10396&t=k04JtqzquEr0TYAo-1)

**Comment by MelissaAutumn** [comment] 2024-09-12 15:55
This was caused by a mixup when adjusting colours for darkmode. Oops. 

Should be fixed in the next push:
<img width="851" alt="image" src="https://github.com/user-attachments/assets/b7faf711-4f45-4679-9bc7-ec1ad494de73">

**Closed as completed by MelissaAutumn** 2024-09-12 15:55 UTC
Labels: bug
